StylesPath = styles
MinAlertLevel = suggestion
Vocab = Project

[*.md]
BasedOnStyles = Vale, ProseAU

# Ignore fenced code blocks and inline code
BlockIgnores = (?sm)^```.*?^```
TokenIgnores = (?s)`[^`]+`, \[[a-z0-9-]+\]

# Don't complain about pass-through tokens / URLs
Vale.Spelling = NO
